# Generated by Django 4.2 on 2026-05-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='growing_house',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
