# Generated by Django 6.0.5 on 2026-05-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stock_growing_house_stock_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['item_id', 'expiry_date']},
        ),
        migrations.AddField(
            model_name='stock',
            name='batch',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='unit_quantity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_id',
            field=models.CharField(max_length=10),
        ),
    ]
