# Generated by Django 6.0.5 on 2026-06-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stock_options_stock_batch_stock_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
