# Generated by Django 4.2 on 2026-05-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growing_house', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('item_id', models.CharField(max_length=10)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('recorded_by', models.CharField(max_length=100)),
                ('date_consumed', models.DateField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'consumption',
            },
        ),
    ]
