# Generated by Django 6.0.5 on 2026-05-27 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_initial'),
        ('stock', '0003_alter_stock_options_stock_batch_stock_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionBatchDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_deducted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_deductions', to='consumption.consumption')),
                ('stock_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stock')),
            ],
            options={
                'db_table': 'consumption_batch_deductions',
            },
        ),
    ]
