# Generated by Django 4.2 on 2026-05-24 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flock', '0002_flocksnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickenProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growing_house', models.CharField(max_length=100)),
                ('harvest_date', models.DateField()),
                ('total_harvested', models.PositiveIntegerField()),
                ('good_chickens', models.PositiveIntegerField()),
                ('rejected', models.PositiveIntegerField()),
                ('flock_count', models.PositiveIntegerField()),
                ('harvest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_per_chicken', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recorded_by', models.CharField(max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('flock', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flock.flock')),
            ],
            options={
                'db_table': 'chicken_production',
                'ordering': ['-harvest_date'],
            },
        ),
    ]
