# Generated by Django 4.2 on 2026-05-23 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Growing', 'Growing'), ('Laying', 'Laying')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('day', models.PositiveIntegerField()),
                ('medicine', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('method', models.CharField(choices=[('Drinking Water', 'Drinking Water'), ('Eye Drop', 'Eye Drop'), ('Injection', 'Injection'), ('Spray', 'Spray')], max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='program.program')),
            ],
            options={
                'ordering': ['week', 'day'],
            },
        ),
    ]
