# Generated by Django 4.2 on 2026-05-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programstep',
            name='dosage',
        ),
        migrations.AddField(
            model_name='programstep',
            name='dose_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programstep',
            name='dose_per',
            field=models.CharField(choices=[('chick', 'chick'), ('liter', 'liter'), ('kg', 'kg')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programstep',
            name='dose_unit',
            field=models.CharField(choices=[('ml', 'ml'), ('g', 'g'), ('L', 'L'), ('tablet', 'tablet'), ('drop', 'drop')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
