# Generated by Django 4.2 on 2026-05-20 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=100)),
                ('growing_house', models.CharField(max_length=50)),
                ('week_number', models.IntegerField()),
                ('snapshot_date', models.DateField()),
                ('start_count', models.IntegerField()),
                ('deaths_this_week', models.IntegerField()),
                ('count_at_snapshot', models.IntegerField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flock.flock')),
            ],
            options={
                'db_table': 'flock_snapshots',
            },
        ),
    ]
