# Generated by Django 4.2 on 2026-05-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_config', '0002_building_category_cause_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Growing', 'Growing'), ('Laying', 'Laying')], max_length=10)),
                ('monthly_target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('set_by', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'config_sales_targets',
                'ordering': ['type', 'building'],
            },
        ),
    ]
