# Generated by Django 4.2 on 2026-05-24 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_config', '0003_salestarget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salestarget',
            options={'ordering': ['-period_start', 'type', 'building']},
        ),
        migrations.RenameField(
            model_name='salestarget',
            old_name='monthly_target',
            new_name='target_revenue',
        ),
        migrations.AddField(
            model_name='salestarget',
            name='period_end',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salestarget',
            name='period_start',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salestarget',
            name='building',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
