# Generated by Django 4.2 on 2026-05-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_config', '0004_alter_salestarget_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickenPriceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_chicken', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField()),
                ('set_by', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chicken_price_config',
                'ordering': ['-effective_date'],
            },
        ),
    ]
