# Generated by Django 6.0.5 on 2026-06-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_config', '0005_chickenpriceconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='UoMConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_unit', models.CharField(max_length=50)),
                ('to_unit', models.CharField(max_length=50)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'config_uom_conversions',
                'ordering': ['from_unit'],
                'unique_together': {('from_unit', 'to_unit')},
            },
        ),
    ]
