# Generated by Django 4.2 on 2026-05-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EggProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flock_id', models.IntegerField()),
                ('building', models.CharField(max_length=50)),
                ('collection_date', models.DateField()),
                ('total_eggs', models.IntegerField()),
                ('good_eggs', models.IntegerField()),
                ('cracked_eggs', models.IntegerField()),
                ('hen_count', models.IntegerField()),
                ('production_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_per_egg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorded_by', models.CharField(max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'egg_production',
                'ordering': ['-collection_date'],
            },
        ),
    ]
