# Generated by Django 4.2 on 2026-05-21 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LayingFlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=50)),
                ('start_count', models.IntegerField()),
                ('current_count', models.IntegerField()),
                ('date_placed', models.DateField()),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'laying_flocks',
            },
        ),
        migrations.CreateModel(
            name='LayingMortality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=50)),
                ('death_date', models.DateField()),
                ('count', models.IntegerField()),
                ('cause', models.CharField(blank=True, max_length=100)),
                ('recorded_by', models.CharField(max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laying_flock.layingflock')),
            ],
            options={
                'db_table': 'laying_mortality',
            },
        ),
    ]
