# Generated by Django 6.0.5 on 2026-06-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='map_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='material',
            name='total_stock_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='material',
            name='total_stock_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
