# Generated by Django 4.2 on 2026-05-24 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        ('flock', '0002_flocksnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayingSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=100)),
                ('eggs_sold', models.PositiveIntegerField()),
                ('price_per_egg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('recorded_by', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.customer')),
            ],
            options={
                'db_table': 'laying_sales',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='GrowingSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_head', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('recorded_by', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.customer')),
                ('flock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flock.flock')),
            ],
            options={
                'db_table': 'growing_sales',
                'ordering': ['-sale_date'],
            },
        ),
    ]
