# Generated by Django 4.2 on 2026-05-24 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0002_flocksnapshot'),
        ('master_data', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growingsale',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.customer'),
        ),
        migrations.AlterField(
            model_name='growingsale',
            name='flock',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flock.flock'),
        ),
        migrations.AlterField(
            model_name='layingsale',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.customer'),
        ),
    ]
